"""Curated seed of major 2026 market-relevant events with hand-assigned tags.

Compiled from three sources, merged and deduped by hand:

1. ``_WIKI_SEED`` — events from Wikipedia's "2026" / "2026 in the United
   States" / current-events pages, each with a real article link.
2. ``_GAUGE_SEED`` — events ported from the frozen reference file
   ``ai_market_sentiment_gauge.html`` (itself compiled from public reporting:
   BLS, BEA, Fed/FOMC releases, earnings, SEC filings, Reuters/CNBC/Bloomberg
   and others through July 2026). Direction comes from the gauge's column,
   ``date_label`` preserves its original fuzzy date.
3. ``_RESEARCH_SEED`` — gap-fill events researched from Wikipedia current-events
   portals and news sources for July 18 – August 18, 2026.

Every row carries exactly one value per tag dimension (category / actor /
direction / region / impact). ``actor`` may be None when the event is neither
government nor company driven. Nothing here is fabricated: each entry traces
to one of the three sources above; entries without a confident article link
use an internal ``seed://`` link and render without a hyperlink in the UI.
"""

from typing import Any

# ---------------------------------------------------------------- source 1
# Wikipedia-linked events (kept from the original seed, re-tagged).
_WIKI_SEED: list[dict[str, Any]] = [
    {"date": "2026-01-01", "date_label": None,
     "title": "Bulgaria adopts the euro as 21st eurozone member",
     "summary": "Bulgaria adopts the euro as the 21st eurozone member.",
     "link": "https://en.wikipedia.org/wiki/Bulgaria_and_the_euro",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "europe", "impact": "High"},
    {"date": "2026-01-03", "date_label": None,
     "title": "US launches airstrikes on Venezuela, captures President Maduro",
     "summary": "Operation Absolute Resolve: US airstrikes on Venezuela and capture of President Nicolas Maduro and his wife.",
     "link": "https://en.wikipedia.org/wiki/2026_United_States_intervention_in_Venezuela",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "global", "impact": "Critical"},
    {"date": "2026-01-07", "date_label": None,
     "title": "US seizes Russian shadow fleet tankers under oil blockade",
     "summary": "US seizes Russian shadow-fleet tankers under the oil blockade during Operation Southern Spear.",
     "link": "https://en.wikipedia.org/wiki/United_States_oil_blockade_during_Operation_Southern_Spear",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "russia-ukraine", "impact": "Critical"},
    {"date": "2026-01-11", "date_label": None,
     "title": "Federal prosecutors open investigation into Fed Chair Jerome Powell",
     "summary": "Federal prosecutors open an investigation into Fed Chair Jerome Powell, escalating pressure on the central bank's independence.",
     "link": "https://en.wikipedia.org/wiki/Jerome_Powell",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-01-17", "date_label": None,
     "title": "Trump confirms 10% tariffs on Europe amid Greenland dispute",
     "summary": "Trump confirms 10% tariffs on Europe amid the Greenland dispute.",
     "link": "https://en.wikipedia.org/wiki/Greenland_crisis",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "europe", "impact": "Critical"},
    {"date": "2026-01-19", "date_label": None,
     "title": "World Economic Forum annual meeting held in Davos",
     "summary": "The 56th World Economic Forum annual meeting is held in Davos.",
     "link": "https://en.wikipedia.org/wiki/56th_World_Economic_Forum",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "global", "impact": "High"},
    {"date": "2026-01-27", "date_label": None,
     "title": "Nvidia shares plunge 17%, largest single-day loss ever",
     "summary": "Nvidia shares plunge 17% in the largest single-day market-cap loss ever recorded.",
     "link": "https://en.wikipedia.org/wiki/Nvidia",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-01-27", "date_label": None,
     "title": "India and European Union sign free trade agreement",
     "summary": "India and the European Union sign a free trade agreement.",
     "link": "https://en.wikipedia.org/wiki/India%E2%80%93European_Union_Free_Trade_Agreement",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "global", "impact": "High"},
    {"date": "2026-01-31", "date_label": None,
     "title": "US federal government shutdown begins",
     "summary": "First of two 2026 partial US federal government shutdowns begins (Jan 31 - Feb 3).",
     "link": "https://en.wikipedia.org/wiki/January%E2%80%93February_2026_United_States_federal_government_shutdown",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-02-05", "date_label": None,
     "title": "New START nuclear arms treaty with Russia expires",
     "summary": "The New START nuclear arms treaty with Russia expires with no replacement.",
     "link": "https://en.wikipedia.org/wiki/New_START",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "russia-ukraine", "impact": "High"},
    {"date": "2026-02-08", "date_label": None,
     "title": "Takaichi wins landslide in Japanese general election",
     "summary": "Takaichi wins a landslide in the Japanese general election.",
     "link": "https://en.wikipedia.org/wiki/2026_Japanese_general_election",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "japan", "impact": "High"},
    {"date": "2026-02-14", "date_label": None,
     "title": "Second federal government shutdown affects Homeland Security",
     "summary": "Second 2026 partial shutdown begins (Feb 14 - Apr 30), the longest in US history, hitting the Department of Homeland Security over ICE funding.",
     "link": "https://en.wikipedia.org/wiki/2026_United_States_federal_government_shutdowns",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-02-20", "date_label": None,
     "title": "Supreme Court strikes down Trump's emergency IEEPA tariffs",
     "summary": "Supreme Court strikes down Trump's emergency IEEPA tariffs (Learning Resources, Inc. v. Trump).",
     "link": "https://en.wikipedia.org/wiki/Learning_Resources,_Inc._v._Trump",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-02-24", "date_label": None,
     "title": "Meta agrees to buy AMD AI chips with share warrants",
     "summary": "Meta agrees to buy AMD AI chips with share warrants.",
     "link": "https://en.wikipedia.org/wiki/AMD",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-02-28", "date_label": None,
     "title": "US and Israel strike Iran, assassinate Supreme Leader Khamenei",
     "summary": "US and Israel strike Iran with the stated goal of regime change, killing Supreme Leader Ali Khamenei.",
     "link": "https://en.wikipedia.org/wiki/2026_Iran_war",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-02-28", "date_label": None,
     "title": "Iran closes the Strait of Hormuz to shipping",
     "summary": "Iran closes the Strait of Hormuz to shipping, the start of the 2026 Hormuz crisis.",
     "link": "https://en.wikipedia.org/wiki/2026_Strait_of_Hormuz_crisis",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-03-13", "date_label": None,
     "title": "US bombs Kharg Island, Iran's main oil export hub",
     "summary": "US bombs Kharg Island, Iran's main oil export hub.",
     "link": "https://en.wikipedia.org/wiki/2026_Kharg_Island_raid",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-04-10", "date_label": None,
     "title": "US inflation hits 3.3% year-on-year, two-year high",
     "summary": "US inflation hits 3.3% year-on-year, a two-year high.",
     "link": "seed://20260410-us-inflation-33",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-04-13", "date_label": None,
     "title": "United States begins naval blockade of Iran",
     "summary": "United States begins a naval blockade of Iran.",
     "link": "https://en.wikipedia.org/wiki/2026_United_States_naval_blockade_of_Iran",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-04-20", "date_label": None,
     "title": "Tim Cook to step down as Apple CEO",
     "summary": "Tim Cook announces he will step down as Apple CEO.",
     "link": "https://en.wikipedia.org/wiki/Tim_Cook",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-04-23", "date_label": None,
     "title": "Warner Bros Discovery approves $111 billion Paramount merger",
     "summary": "Warner Bros Discovery board approves the $111 billion Paramount merger.",
     "link": "https://en.wikipedia.org/wiki/Warner_Bros._Discovery",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-04-30", "date_label": None,
     "title": "76-day partial government shutdown ends",
     "summary": "The 76-day partial government shutdown, the longest in US history, ends.",
     "link": "seed://20260430-shutdown-ends",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-05-01", "date_label": None,
     "title": "United Arab Emirates leaves OPEC after six decades",
     "summary": "United Arab Emirates leaves OPEC after six decades, reshaping the oil cartel.",
     "link": "https://en.wikipedia.org/wiki/OPEC",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-05-02", "date_label": None,
     "title": "Spirit Airlines goes out of business",
     "summary": "Spirit Airlines ceases operations.",
     "link": "https://en.wikipedia.org/wiki/Spirit_Airlines",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-05-08", "date_label": None,
     "title": "US court rules Trump's global tariffs illegal",
     "summary": "US court rules Trump's global tariffs illegal.",
     "link": "https://en.wikipedia.org/wiki/Tariffs_in_the_second_Trump_administration",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-05-13", "date_label": None,
     "title": "Senate confirms Kevin Warsh as Federal Reserve Chair",
     "summary": "Senate confirms Kevin Warsh as Fed Chair 54-45; hawkish tone from day one, dot plot signals a possible hike, not a cut.",
     "link": "https://en.wikipedia.org/wiki/Kevin_Warsh",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-12", "date_label": None,
     "title": "SpaceX makes largest-ever IPO at $2 trillion valuation",
     "summary": "IPO prices at $135, rockets to $225, then gives back ~32-40% of the gain - dents confidence in mega-cap AI-adjacent listings just as OpenAI and Anthropic file.",
     "link": "https://en.wikipedia.org/wiki/Initial_public_offering_of_SpaceX",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-15", "date_label": None,
     "title": "US and Iran sign Islamabad Memorandum ending war",
     "summary": "US and Iran sign the Islamabad Memorandum, ending the 2026 Iran war.",
     "link": "https://en.wikipedia.org/wiki/Islamabad_Memorandum",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-06-16", "date_label": None,
     "title": "SpaceX to acquire Cursor for $60 billion",
     "summary": "SpaceX agrees to acquire Cursor for $60 billion.",
     "link": "https://en.wikipedia.org/wiki/Cursor_(company)",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-06-29", "date_label": None,
     "title": "Supreme Court blocks Trump's removal of Fed governor Lisa Cook",
     "summary": "Supreme Court blocks Trump's removal of Fed governor Lisa Cook, defending Fed independence.",
     "link": "https://en.wikipedia.org/wiki/Lisa_D._Cook",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-07-01", "date_label": None,
     "title": "US announces it will not renew USMCA trade deal",
     "summary": "US announces it will not renew the USMCA trade deal.",
     "link": "https://en.wikipedia.org/wiki/United_States%E2%80%93Mexico%E2%80%93Canada_Agreement",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-13", "date_label": None,
     "title": "Trump reinstates Iran blockade and 20% Hormuz toll",
     "summary": "Trump reinstates the Iran blockade and imposes a 20% Strait of Hormuz toll.",
     "link": "seed://20260713-iran-blockade-reinstated",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-20", "date_label": None,
     "title": "Houthis announce maritime blockade of Saudi Arabia",
     "summary": "Houthis announce a maritime blockade of Saudi Arabia, effective immediately.",
     "link": "https://en.wikipedia.org/wiki/Houthi_blockade_of_Saudi_Arabia",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-23", "date_label": None,
     "title": "US imposes tariffs on 60 major trading partners",
     "summary": "US imposes 10-12.5% tariffs on 60 trading partners (99.4% of imports) over forced labor.",
     "link": "https://en.wikipedia.org/wiki/United_States_Trade_Representative",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-30", "date_label": None,
     "title": "Saudi Arabia forms 14-nation maritime defense alliance",
     "summary": "Saudi Arabia forms a 14-nation Multinational Maritime Defense Alliance to keep Bab-el-Mandeb open.",
     "link": "https://en.wikipedia.org/wiki/Multinational_Maritime_Defense_Alliance",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "High"},
    {"date": "2026-08-05", "date_label": None,
     "title": "$55 billion leveraged buyout of Electronic Arts completed",
     "summary": "$55 billion leveraged buyout of Electronic Arts completed.",
     "link": "https://en.wikipedia.org/wiki/Leveraged_buyout_of_Electronic_Arts",
     "source": "Wikipedia", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-08-14", "date_label": None,
     "title": "Trump says US will annex Strait of Hormuz",
     "summary": "Trump says the US will declare the Strait of Hormuz a US territory 'pretty soon'.",
     "link": "https://en.wikipedia.org/wiki/American_expansionism_under_Donald_Trump",
     "source": "Wikipedia", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
]

# ---------------------------------------------------------------- source 2
# Events ported from the frozen ai_market_sentiment_gauge.html. Direction
# follows the gauge's column; date_label preserves its original fuzzy label.
_GAUGE_SEED: list[dict[str, Any]] = [
    {"date": "2026-01-14", "date_label": "Jan 14-15, 2026",
     "title": "Trump signs Section 232: 25% tariff on advanced computing chips",
     "summary": "Trump signs Section 232 proclamation: 25% tariff on advanced computing chips effective Jan 15; ITIF estimates a cumulative $1.6T GDP hit over 10 years if sustained.",
     "link": "seed://20260114-section-232-chip-tariff",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-01-15", "date_label": "Jan 2026",
     "title": "Private credit default rate hits 5.8%, highest on record",
     "summary": "Private credit default rate hits 5.8% trailing 12-month, the highest on record.",
     "link": "seed://20260115-private-credit-default-rate",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-01-15", "date_label": "Jan 2026",
     "title": "Oracle CDS spread jumps ~310%, Stargate debt syndication stalls",
     "summary": "Oracle's 5-yr CDS spread jumps ~310%, credit watch negative; JPMorgan struggles to syndicate Stargate-linked debt.",
     "link": "https://en.wikipedia.org/wiki/Oracle_Corporation",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-01-15", "date_label": "Jan 2026",
     "title": "Office CMBS delinquency hits record 12.34%",
     "summary": "Office CMBS delinquency hits a record 12.34%; ~$930B of CRE loans mature in 2026, ~$126B already distressed.",
     "link": "seed://20260115-office-cmbs-delinquency",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-01-15", "date_label": "Jan/Feb/Jun 2026",
     "title": "China escalates export bans on Japan across three rounds",
     "summary": "China escalates export bans on Japan across three rounds - rare-earth and dual-use chokehold, 80+ entities blacklisted.",
     "link": "seed://20260115-china-export-bans-japan",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "japan", "impact": "Critical"},
    {"date": "2026-02-15", "date_label": "Feb 2026",
     "title": "Amazon guides to ~$200B of 2026 capex, stock sinks ~6%",
     "summary": "Amazon guides to ~$200B of 2026 capex, the most aggressive of the hyperscalers; stock sinks ~6% on free-cash-flow concerns despite beating revenue.",
     "link": "https://en.wikipedia.org/wiki/Amazon_(company)",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-02-15", "date_label": "Q1 2026",
     "title": "RAM chip prices surge ~90% in Q1 2026",
     "summary": "RAM chip prices surge ~90% in Q1 2026 alone, pushing up costs for PCs, laptops and phones - input-cost inflation compounding the new chip tariff.",
     "link": "seed://20260215-ram-chip-prices",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "global", "impact": "High"},
    {"date": "2026-04-15", "date_label": "Apr 2026",
     "title": "Meta raises 2026 capex to $125-135B, stock falls ~6%",
     "summary": "Meta raises 2026 capex to $125-135B without proportional revenue proof; stock falls ~6%. Barclays models negative free cash flow for Meta into 2027-28.",
     "link": "https://en.wikipedia.org/wiki/Meta_Platforms",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-05-15", "date_label": "May 2026",
     "title": "Headline CPI hits 4.17% YoY, fourth straight rising month",
     "summary": "Headline CPI hits 4.17% YoY, a 4th straight rising month - highest since April 2023 (later reversed in June).",
     "link": "seed://20260515-cpi-417",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "June FOMC holds rates at 3.50-3.75%, drops easing bias",
     "summary": "June FOMC holds rates at 3.50-3.75%, drops 'easing bias' language; 9 of 18 officials pencil in a 2026 hike.",
     "link": "https://en.wikipedia.org/wiki/Federal_Open_Market_Committee",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "US antitrust suit accuses Samsung, SK Hynix, Micron of engineering memory shortage",
     "summary": "US antitrust suit accuses Samsung, SK Hynix and Micron of engineering a memory shortage via the shift to HBM.",
     "link": "https://en.wikipedia.org/wiki/SK_Hynix",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "korea", "impact": "High"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "June jobs report: only 57K added vs 115K expected",
     "summary": "June jobs report: only 57K added vs 115K expected; April-May revised down a combined 74K; labor-force participation falls to a 5-yr low.",
     "link": "https://en.wikipedia.org/wiki/United_States_Department_of_Labor",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "Nvidia's valuation approaches $5 trillion",
     "summary": "Nvidia's valuation approaches $5 trillion, a level reporting describes as 'making many investors nervous' even before the July selloff.",
     "link": "seed://20260615-nvidia-5-trillion",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "Michael Burry publishes 'fugazi' critique of AI deal structures",
     "summary": "Michael Burry publishes a 'fugazi' critique alleging Nvidia/OpenAI/xAI deal structures (SPVs, offshore insurers) shift AI infrastructure risk onto pensions and retail investors.",
     "link": "https://en.wikipedia.org/wiki/Michael_Burry",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "OpenAI weighing delaying its IPO into 2027",
     "summary": "Bloomberg reports OpenAI is weighing delaying its IPO into 2027 amid post-SpaceX market volatility.",
     "link": "seed://20260615-openai-ipo-delay",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-07-18", "date_label": "Jun-Jul 2026",
     "title": "US-Iran ceasefire collapses; strikes resume",
     "summary": "US-Iran ceasefire collapses; Trump declares the MOU 'over,' strikes resume, Strait of Hormuz risk returns. Iran suspends its Islamabad Memorandum commitments, accusing the US of breaching the deal.",
     "link": "seed://20260718-iran-ceasefire-collapse",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "10-yr Treasury yield near 7-week high (~4.5-4.6%)",
     "summary": "10-yr Treasury yield near a 7-week high (~4.5-4.6%) on Iran-driven inflation fears.",
     "link": "https://en.wikipedia.org/wiki/United_States_Treasury_security",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-01", "date_label": "Jul 1, 2026",
     "title": "Fed Chair Warsh at Sintra: inflation still 'too high'",
     "summary": "Fed Chair Warsh, at Sintra: inflation still 'too high,' resists signaling cuts despite open-mindedness on AI productivity.",
     "link": "seed://20260701-warsh-sintra",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-14", "date_label": "Jul 14, 2026",
     "title": "NY signs first statewide moratorium on new hyperscale data centers",
     "summary": "NY Gov. Hochul signs the nation's first statewide moratorium on new hyperscale (50MW+) data centers.",
     "link": "seed://20260714-hyperscale-moratorium-ny",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "Sector-wide AI chip selloff: SOXX -5.1% in a single session",
     "summary": "Sector-wide AI chip selloff: SOXX -5.1% in a single session, semiconductor ETF down >17% for the month.",
     "link": "https://en.wikipedia.org/wiki/IShares_Semiconductor_ETF",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "Samsung Q2 profit up ~19x YoY but stock falls ~7%",
     "summary": "Samsung Q2 profit up ~19x YoY on HBM demand but the stock falls ~7% anyway - market reads it as 'priced for perfection.'",
     "link": "https://en.wikipedia.org/wiki/Samsung_Electronics",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "korea", "impact": "Critical"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "KOSPI suffers historic ~10% single-day decline",
     "summary": "KOSPI suffers a historic ~10% single-day decline as foreign investors trim Korean semiconductor exposure.",
     "link": "seed://20260715-kospi-crash",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "korea", "impact": "Critical"},
    {"date": "2026-07-17", "date_label": "Jul 17, 2026",
     "title": "Chinese startup Moonshot ships model rivaling OpenAI/Anthropic",
     "summary": "Chinese startup Moonshot ships a model it says rivals OpenAI/Anthropic, pressuring the US AI-moat narrative.",
     "link": "https://en.wikipedia.org/wiki/Moonshot_AI",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "china", "impact": "Critical"},
    {"date": "2026-01-01", "date_label": "2025-26",
     "title": "OpenAI's ~$1T in vendor commitments raises sustainability questions",
     "summary": "OpenAI's ~$1T in vendor commitments raises sustainability questions if usage growth slows.",
     "link": "seed://20260101-openai-vendor-commitments",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "ServiceNow -27%, Palantir -21% YTD on agentic AI cannibalization fears",
     "summary": "ServiceNow -27%, Palantir -21% YTD on fears agentic AI cannibalizes SaaS seat revenue.",
     "link": "seed://20260715-saas-ai-cannibalization",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "Forrester: 41% of enterprises report production AI-agent rollback",
     "summary": "Forrester: 41% of enterprises report at least one production AI-agent rollback in the last 12 months.",
     "link": "seed://20260630-ai-agent-rollbacks",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "800G+ optical transceiver production 40-60% below demand through 2027",
     "summary": "800G+ optical transceiver production running 40-60% below demand through 2027 - supply bottleneck risk.",
     "link": "seed://20260630-optical-transceiver-bottleneck",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "global", "impact": "High"},
    {"date": "2026-07-17", "date_label": "Jul 17, 2026",
     "title": "Bond investors push back: AI-related debt issuance heading toward $570B",
     "summary": "Bond investors push back: AI-related debt issuance heading toward $570B; hyperscaler bond coverage ratios are softening.",
     "link": "seed://20260717-ai-debt-issuance",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "'GPU debt treadmill': GPUs depreciate faster than securitized debt assumes",
     "summary": "'GPU debt treadmill': GPUs depreciate over ~7 years but increasingly back securitized debt structured against 20-30 year data-center lifespans - a structural mismatch.",
     "link": "seed://20260630-gpu-debt-treadmill",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026 est.",
     "title": "Circular financing loop (Nvidia - labs - hyperscalers) tops $800B",
     "summary": "Circular financing loop (Nvidia - labs - hyperscalers) now tops $800B. Bull case: normal vendor-financing that locks in real demand. Bear case (Burry, Chanos): revenue recycling that obscures whether demand is organic.",
     "link": "seed://20260630-circular-financing-loop",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-05-15", "date_label": "May-Jun 2026",
     "title": "Q1 2026 GDP revised up to 2.1% but growth is narrow",
     "summary": "Q1 2026 GDP revised up to 2.1% annualized - but the growth is narrow: corporate/AI capex did the lifting while consumer spending growth was revised down sharply.",
     "link": "https://en.wikipedia.org/wiki/Economy_of_the_United_States",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-02-15", "date_label": "Q1 2026",
     "title": "Gartner: 80% of new enterprise apps embed an AI agent, 31% in production",
     "summary": "Gartner: 80% of new enterprise apps now embed an AI agent, but only 31% have one in production - adoption is broad but still shallow.",
     "link": "seed://20260215-gartner-ai-agents",
     "source": "Curated (gauge)", "category": "macro", "actor": None,
     "direction": "neutral", "region": "global", "impact": "High"},
    {"date": "2026-06-30", "date_label": "Mid-2026",
     "title": "China's domestic chips remain 3-5 years behind US-Taiwan frontier",
     "summary": "China's domestic chips remain an estimated 3-5 years behind the US-Taiwan frontier; CUDA lock-in still slows any real switch to Huawei's stack.",
     "link": "https://en.wikipedia.org/wiki/Semiconductor_industry_in_China",
     "source": "Curated (gauge)", "category": "macro", "actor": "company",
     "direction": "neutral", "region": "china", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "New EU compute package lifts European AI investment somewhat",
     "summary": "New EU compute package should lift European AI investment somewhat, but analysts don't expect it to close the structural gap to the US.",
     "link": "seed://20260630-eu-compute-package",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "europe", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "Unemployment fell to 4.2% but participation is at a 5-yr low",
     "summary": "Unemployment fell to 4.2% in June - but the improvement is driven by workers leaving the labor force (participation at a 5-yr low), not stronger hiring.",
     "link": "https://en.wikipedia.org/wiki/Unemployment_in_the_United_States",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-07-15", "date_label": "Jul-Aug 2026",
     "title": "2026 midterm primary season underway; AI-backed super PAC active",
     "summary": "2026 midterm primary season is underway (general election Nov 3); an AI-backed super PAC is now active in multiple GOP primaries - political direction on AI policy is still unresolved.",
     "link": "https://en.wikipedia.org/wiki/2026_United_States_elections",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-06-01", "date_label": "Jun 1 & 8, 2026",
     "title": "Anthropic and OpenAI both file confidentially for IPOs",
     "summary": "Anthropic and OpenAI both file confidentially for IPOs ($965B and up to $850B target valuations) - a real market test of AI valuations is coming this fall, outcome unknown.",
     "link": "seed://20260601-anthropic-openai-ipo-filings",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "us", "impact": "High"},
    {"date": "2026-01-01", "date_label": "Ongoing 2025-26",
     "title": "TSMC CoWoS capacity expanding ~80%/yr: 35K to 130K wafers/month",
     "summary": "TSMC CoWoS capacity expanding ~80%/yr: 35K to 130K wafers/month by end of 2026.",
     "link": "seed://20260101-tsmc-cowos-expansion",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "global", "impact": "High"},
    {"date": "2026-01-15", "date_label": "Jan 2026",
     "title": "BIS eases China export-license review to case-by-case",
     "summary": "BIS shifts China export-license review from presumption-of-denial to case-by-case for advanced chips (with exporter certification) - eases one supply-chain constraint.",
     "link": "https://en.wikipedia.org/wiki/Bureau_of_Industry_and_Security",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "china", "impact": "High"},
    {"date": "2026-01-15", "date_label": "Jan 2026",
     "title": "OpenAI annualized revenue passes $20B in January 2026",
     "summary": "OpenAI's CFO confirms annualized revenue passed $20B in January 2026, up from ~$6B in 2024.",
     "link": "https://en.wikipedia.org/wiki/OpenAI",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-02-15", "date_label": "Feb 2026",
     "title": "Big Tech capex tracks to ~$700B for 2026",
     "summary": "Big Tech capex tracks to ~$700B for 2026; Microsoft discloses an $80B Azure order backlog it can't fill due to power constraints - demand still outrunning supply.",
     "link": "seed://20260215-big-tech-capex-2026",
     "source": "Curated (gauge)", "category": "macro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-03-02", "date_label": "Mar 2, 2026",
     "title": "Nvidia locks up $4B of EML laser supply via Lumentum + Coherent",
     "summary": "Nvidia locks up $4B of EML laser supply via Lumentum + Coherent, pushing rivals past 2027.",
     "link": "seed://20260302-nvidia-eml-laser",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-03-15", "date_label": "Mar 2026",
     "title": "China's 15th Five-Year Plan embeds AI as national priority",
     "summary": "China's 15th Five-Year Plan embeds AI as a national priority on par with defense.",
     "link": "https://en.wikipedia.org/wiki/Five-year_plans_of_China",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "china", "impact": "High"},
    {"date": "2026-02-15", "date_label": "Feb-Apr 2026",
     "title": "Japan pushes Rapidus funding to 2.6T yen chasing 2nm by 2027",
     "summary": "Japan pushes Rapidus funding to 2.6T yen ($16.3B) chasing 2nm by 2027; SoftBank+Sony+Honda+NEC launch a $1.3B AI consortium.",
     "link": "https://en.wikipedia.org/wiki/Rapidus",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "japan", "impact": "High"},
    {"date": "2026-04-15", "date_label": "Apr 2026",
     "title": "CoreWeave secures $8.5B first investment-grade GPU-backed loan",
     "summary": "CoreWeave secures $8.5B in the first investment-grade-rated GPU-backed loan; stock jumps 12% - validates GPU-backed lending as an institutional asset class.",
     "link": "https://en.wikipedia.org/wiki/CoreWeave",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-04-30", "date_label": "Apr 30, 2026",
     "title": "Google Cloud revenue +63% YoY to $20B, backlog $240B+",
     "summary": "Google Cloud revenue +63% YoY to $20B, backlog +55% sequentially to $240B+; Alphabet stock +6.4% on the print.",
     "link": "https://en.wikipedia.org/wiki/Google_Cloud",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-05-06", "date_label": "May 6, 2026",
     "title": "Palantir Q1: revenue $1.6B, +85% YoY",
     "summary": "Palantir Q1: revenue $1.6B, +85% YoY; $1.2B of US commercial bookings in the quarter.",
     "link": "https://en.wikipedia.org/wiki/Palantir_Technologies",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "Salesforce Agentforce hits $800M ARR, +169% YoY",
     "summary": "Salesforce Agentforce hits $800M ARR, +169% YoY, 29,000+ deals closed.",
     "link": "https://en.wikipedia.org/wiki/Salesforce",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-04-08", "date_label": "Apr 8, 2026",
     "title": "US-Iran ceasefire reached, briefly easing oil/inflation risk",
     "summary": "US-Iran ceasefire reached, briefly easing oil/inflation risk (later collapses in July).",
     "link": "https://en.wikipedia.org/wiki/2025%E2%80%932026_Iran%E2%80%93United_States_negotiations",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "middle-east", "impact": "High"},
    {"date": "2026-05-15", "date_label": "May 2026",
     "title": "South Korea exports +53.2% YoY to a record $87.75B",
     "summary": "South Korea exports +53.2% YoY to a record $87.75B; semiconductor exports alone +169.4%, driven by HBM/DRAM pricing.",
     "link": "https://en.wikipedia.org/wiki/Economy_of_South_Korea",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "korea", "impact": "Critical"},
    {"date": "2026-05-15", "date_label": "YTD May 2026",
     "title": "KOSPI up ~90-100% YTD, led by Samsung and SK Hynix",
     "summary": "KOSPI up ~90-100% YTD, led by Samsung and SK Hynix.",
     "link": "seed://20260515-kospi-ytd",
     "source": "Curated (gauge)", "category": "macro", "actor": "company",
     "direction": "bullish", "region": "korea", "impact": "High"},
    {"date": "2026-05-15", "date_label": "May 2026",
     "title": "Bank of Korea and KDI raise 2026 GDP growth forecasts",
     "summary": "Bank of Korea and KDI both raise 2026 GDP growth forecasts, largely on the chip supercycle.",
     "link": "https://en.wikipedia.org/wiki/Bank_of_Korea",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "korea", "impact": "High"},
    {"date": "2026-05-15", "date_label": "May 2026",
     "title": "Anthropic annualized revenue jumps to $44B+, overtakes OpenAI enterprise share",
     "summary": "Anthropic's annualized revenue jumps from ~$9B (end-2025) to $44B+ (May 2026); overtakes OpenAI in enterprise AI market share.",
     "link": "seed://20260515-anthropic-revenue",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-06-15", "date_label": "Jun 2026",
     "title": "June CPI cools sharply: -0.4% MoM, biggest monthly drop since April 2020",
     "summary": "June CPI cools sharply: -0.4% MoM, the biggest monthly drop since April 2020; core steady at 2.6% YoY.",
     "link": "https://en.wikipedia.org/wiki/United_States_Consumer_Price_Index",
     "source": "Curated (gauge)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-05-15", "date_label": "Q2 2026",
     "title": "Anthropic posts first profitable quarter: ~$10.9B revenue",
     "summary": "Anthropic posts its first profitable quarter: ~$10.9B Q2 revenue, ~$559M operating income.",
     "link": "https://en.wikipedia.org/wiki/Anthropic",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-16", "date_label": "Jul 16, 2026",
     "title": "TSMC posts record Q2 profit, raises guidance, +$100B Arizona investment",
     "summary": "TSMC posts record Q2 profit, raises FY revenue and capex guidance, and announces an additional $100B Arizona investment.",
     "link": "https://en.wikipedia.org/wiki/TSMC",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "global", "impact": "Critical"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "Nvidia data-center revenue still growing 75%+ YoY through mid-2026",
     "summary": "Nvidia data-center revenue still growing 75%+ YoY through mid-2026 - hyperscaler capex guidance is still rising, not cooling.",
     "link": "seed://20260630-nvidia-dc-revenue",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-15", "date_label": "Jul 2026",
     "title": "Micron +209% YTD, SanDisk +506% YTD despite July pullback",
     "summary": "Despite the July pullback, Micron is +209% YTD and SanDisk +506% YTD - the memory-supercycle rally is mostly intact.",
     "link": "https://en.wikipedia.org/wiki/Micron_Technology",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-06-30", "date_label": "2026",
     "title": "Huawei AI chip revenue set to hit ~$12B (+60% YoY)",
     "summary": "Huawei AI chip revenue set to hit ~$12B (+60% YoY) as China builds a parallel hardware/software stack.",
     "link": "https://en.wikipedia.org/wiki/Huawei",
     "source": "Curated (gauge)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "china", "impact": "High"},
]

# ---------------------------------------------------------------- source 3
# Researched gap-fill: July 18 - August 18, 2026 (Wikipedia current-events
# portals + linked news sources). Deduped against sources 1 and 2 by hand.
_RESEARCH_SEED: list[dict[str, Any]] = [
    {"date": "2026-07-20", "date_label": None,
     "title": "Brent crude tops $90, US gasoline passes $4/gal as Iran escalation resumes",
     "summary": "Brent crude tops $90 and US gasoline passes $4/gal as the Iran escalation resumes.",
     "link": "https://www.cnbc.com/2026/07/20/oil-prices-today-brent-wti-crude-us-iran-centcom-hormuz.html",
     "source": "News (researched)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-20", "date_label": None,
     "title": "Trump signs executive order imposing 50% tariffs on many Canadian goods",
     "summary": "Trump signs executive order imposing 50% tariffs on many Canadian goods, including USMCA-covered products.",
     "link": "https://en.wikipedia.org/wiki/2025%E2%80%932026_United_States_trade_war_with_Canada_and_Mexico",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "us", "impact": "Critical"},
    {"date": "2026-07-21", "date_label": None,
     "title": "OpenAI says AI models 'went rogue' during testing, Hugging Face breached",
     "summary": "OpenAI says AI models 'went rogue' during testing, triggering an 'unprecedented' breach at Hugging Face.",
     "link": "https://www.reuters.com/technology/openai-says-ai-models-went-rogue-during-testing-triggering-unprecedented-breach-2026-07-21/",
     "source": "News (researched)", "category": "micro", "actor": "company",
     "direction": "bearish", "region": "us", "impact": "High"},
    {"date": "2026-07-21", "date_label": None,
     "title": "Russia halts bond auctions after sales fail to find buyers",
     "summary": "Russia halts bond auctions after recent sales failed to find buyers.",
     "link": "https://www.bloomberg.com/news/articles/2026-07-21/russia-halts-bond-auctions-with-more-monetary-easing-in-question",
     "source": "News (researched)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "russia-ukraine", "impact": "High"},
    {"date": "2026-07-23", "date_label": None,
     "title": "Brent tops $101, WTI near $93 after Red Sea escalation",
     "summary": "Brent tops $101, WTI near $93, US gasoline $4.09 after the Red Sea escalation.",
     "link": "https://www.nbcnews.com/business/markets/oil-prices-rise-red-sea-attacks-houthis-saudi-trump-iran-war-rcna588851",
     "source": "News (researched)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-27", "date_label": None,
     "title": "Houthi drone attack damages the Abqaiq oil field in Saudi Arabia",
     "summary": "Houthi drone attack damages the Abqaiq oil field in eastern Saudi Arabia.",
     "link": "https://en.wikipedia.org/wiki/Abqaiq_oil_field",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-07-27", "date_label": None,
     "title": "Singapore's MAS tightens policy again, citing Iran-war inflation risks",
     "summary": "Singapore's MAS tightens monetary policy for the second time in three months, citing Iran-war inflation risks.",
     "link": "https://en.wikipedia.org/wiki/Monetary_Authority_of_Singapore",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "global", "impact": "High"},
    {"date": "2026-07-28", "date_label": None,
     "title": "Taiwan detains Nvidia employee in AI-chip smuggling probe to China",
     "summary": "Taiwan detains an Nvidia employee in an AI-chip smuggling probe to China (~50 Supermicro servers).",
     "link": "https://www.france24.com/en/live-news/20260728-taiwan-detains-nvidia-worker-in-chip-smuggling-probe-source-familiar-with-case",
     "source": "News (researched)", "category": "micro", "actor": "company",
     "direction": "neutral", "region": "china", "impact": "High"},
    {"date": "2026-07-28", "date_label": None,
     "title": "Mw 7.1 earthquake strikes Kumamoto, Japan",
     "summary": "Mw 7.1 earthquake strikes Kumamoto, Japan; tsunami alert; toll later rises to 35 dead.",
     "link": "https://en.wikipedia.org/wiki/2026_Kumamoto_earthquake",
     "source": "Wikipedia (current events)", "category": "macro", "actor": None,
     "direction": "bearish", "region": "japan", "impact": "High"},
    {"date": "2026-07-30", "date_label": None,
     "title": "US awards Lockheed Martin record $58.6B Patriot interceptor contract",
     "summary": "US awards Lockheed Martin a record $58.6B Patriot interceptor contract.",
     "link": "https://en.wikipedia.org/wiki/Lockheed_Martin",
     "source": "Wikipedia (current events)", "category": "micro", "actor": "company",
     "direction": "bullish", "region": "us", "impact": "High"},
    {"date": "2026-07-31", "date_label": None,
     "title": "KOSPI surges 18%, largest single-day gain in history",
     "summary": "South Korea's KOSPI surges 18%, its largest single-day gain in history, on the AI investment surge.",
     "link": "seed://20260731-kospi-surge",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "company",
     "direction": "bullish", "region": "korea", "impact": "Critical"},
    {"date": "2026-08-04", "date_label": None,
     "title": "Bulk carrier struck by projectile, missing in Strait of Hormuz",
     "summary": "Bulk carrier Minoan Pioneer struck by projectile and reported missing in the Strait of Hormuz.",
     "link": "seed://20260804-minoan-pioneer-hormuz",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-08-05", "date_label": None,
     "title": "Iran and Oman agree on Hormuz shipping-route coordinates",
     "summary": "Iran and Oman reach agreement on geographic coordinates for shipping routes through the Strait of Hormuz.",
     "link": "https://en.wikipedia.org/wiki/2026_Iran%E2%80%93Oman_negotiations",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "middle-east", "impact": "High"},
    {"date": "2026-08-07", "date_label": None,
     "title": "US Senate passes Russia energy-sanctions bill with 100% tariffs",
     "summary": "US Senate passes (86-11) Russia energy-sanctions bill with 100% tariffs on buyers of Russian oil/gas.",
     "link": "https://en.wikipedia.org/wiki/Sanctioning_Russia_Act",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "russia-ukraine", "impact": "Critical"},
    {"date": "2026-08-08", "date_label": None,
     "title": "Iran says it will reopen Hormuz if US lifts sanctions, ends blockade",
     "summary": "Iran says it will reopen the Strait of Hormuz if the US lifts sanctions and ends its naval blockade.",
     "link": "seed://20260808-iran-hormuz-reopen",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bullish", "region": "middle-east", "impact": "High"},
    {"date": "2026-08-10", "date_label": None,
     "title": "Ukrainian drone attack hits Nizhnekamsk oil refinery in Tatarstan",
     "summary": "Ukrainian drone attack on the Nizhnekamsk oil refinery in Tatarstan kills 13.",
     "link": "https://en.wikipedia.org/wiki/Attacks_in_Russia_during_the_Russo-Ukrainian_war_(2022%E2%80%93present)",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "russia-ukraine", "impact": "High"},
    {"date": "2026-08-13", "date_label": None,
     "title": "UAE says two more ADNOC vessels attacked in Strait of Hormuz",
     "summary": "UAE says two more ADNOC vessels were attacked in the Strait of Hormuz and accuses Iran.",
     "link": "seed://20260813-adnoc-vessels-attacked",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-08-15", "date_label": None,
     "title": "Third ADNOC vessel attacked by Iran in the Strait of Hormuz",
     "summary": "Emirates News Agency reports a third ADNOC vessel attacked by Iran in the Strait of Hormuz.",
     "link": "seed://20260815-third-adnoc-vessel",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
    {"date": "2026-08-17", "date_label": None,
     "title": "Trump orders Pentagon to scale back Ulchi-Freedom Guardian exercises",
     "summary": "Trump orders Pentagon to substantially reduce Ulchi-Freedom Guardian exercises with South Korea.",
     "link": "https://en.wikipedia.org/wiki/Ulchi-Freedom_Guardian",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "neutral", "region": "korea", "impact": "High"},
    {"date": "2026-08-18", "date_label": None,
     "title": "Cargo vessel attacked in Strait of Hormuz, one dead; missiles fired from Iran",
     "summary": "UKMTO: cargo vessel attacked in the Strait of Hormuz, one dead; UAE detects two missiles fired from Iran.",
     "link": "seed://20260818-hormuz-cargo-attack",
     "source": "Wikipedia (current events)", "category": "macro", "actor": "government",
     "direction": "bearish", "region": "middle-east", "impact": "Critical"},
]

SEED_EVENTS: list[dict[str, Any]] = sorted(
    _WIKI_SEED + _GAUGE_SEED + _RESEARCH_SEED, key=lambda e: e["date"]
)
